server:
  port: 8080
  contextPath: /v1


spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:./db/accountdb.db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: true
          format_sql: true

flyway:
  enabled: true
  url: jdbc:h2:file:./db/accountdb.db
  user: sa
  password:
  locations: classpath:db/migration
